# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Milkyway' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'XLPagerTabStrip', '~> 9.0'
  pod 'NMapsMap' 
  pod 'DLRadioButton', '~> 1.4'
  pod 'lottie-ios'
  pod 'SwiftKeychainWrapper' 

  # Pods for Milkyway

end
